/*
    Warning - this file was autogenerated by genparse
    DO NOT EDIT - any changes will be lost
*/

#include "sink_parse.h"

#include <ctype.h>
#include <panic.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <util.h> /* hash and compare */

#if (defined TEST_HARNESS || defined DISPLAY_AT_CMDS)
#include <stdio.h>
#endif
#include "sink_custom_uart.h"

typedef const uint8 *ptr;

static __inline__ char my_toupper(char c)
{ return 'a' <= c && c <= 'z' ? c +'A'-'a' : c; }

static ptr match1(ptr s, ptr e)
{ return s && s != e && (*s == '\r' || *s == '\n') ? s+1 : 0; }

#ifdef TEST_HARNESS
static void printString(const char *name, const struct sequence *s)
{
  uint16 i;
  printf(" %s='", name);
  for(i = 0; i < s->length; ++i) putchar(s->data[i]);
  printf("'");
}
#endif

static __inline__ ptr skipQuote(ptr p, ptr e)
{ return p && p != e && *p == '"' ? p+1 : p; }

static const int isStringTable[] =
{
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    1,0,0,1,0,1,0,1,1,1,1,1,0,1,0,1,
    1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,1,
    0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0
};

static __inline__ int isString(char c)
{
    return (c & ~0x7F) == 0 && isStringTable[(int)c];
}

static ptr getString(ptr p, ptr e, struct sequence *res)
{
  p = skipQuote(p, e);
  if(p)
  {
    ptr s = p;
    while(p != e && isString(*p)) ++p;
    if(p != s)
    {
        res->data = s;
        res->length = p - s;
        return skipQuote(p, e);
    }
    else
    {
        p = skipQuote(p, e);
        if (*p==',' || *p == '\r')
        {
            res->data = 0;
            res->length = 0;
            return p;
        }
    }
  }
  res->data = 0;
  res->length = 0;
  return 0;
}

static ptr findEndOfPacket(ptr s, ptr e)
{
  /*
     Returns
     0   if the buffer holds an incomplete packet
     s+1 if the buffer holds an invalid packet
     end of the first packet otherwise
  */
  if(s == e) return 0;

  if(*s == '\r')
  {
    /* expecting <cr> <lf> ... <cr> <lf> */
    if(e-s >= 4)
    {
      if(s[1] == '\n' && s[2] != '\r')
      {
        ptr p = s+2;
        if(*p != '\r')
        {
#ifndef TEST_HARNESS
        p = (const uint8*)UtilFind(0xFFFF, '\r', (const uint16*)p, 0, 1, (uint16)(e-p));
#endif
#ifdef TEST_HARNESS
		   while(p != e && *p != '\r') p++;
#endif
        return p == 0 || p + 1 == e ? 0 /* no terminator yet */
             : p[1] == '\n' ? p+2 /* valid */
             : s+1 ; /* invalid terminator */
         }
         else
             return s+1;
      }
      else
      {
        return s+1;
      }
    }
    else
    {
      /* Can't tell yet */
      return 0;
    }
  }
  else
  {
    /* expecting ... <cr> */
    ptr p = s;
    while(p != e && (*p == ' ' || *p == '\0' || *p == '\t')) ++p;
    if(p != e && (*p == '\r' || *p == '\n' )) return s+1;
    while(p != e && *p != '\r') ++p;
    return p == e ? 0 : p+1;
  }
}

#ifndef TEST_HARNESS
#ifdef __XAP__
uint16 UartparseSource(Source rfcDataIn, Task task)
{
  ptr s = SourceMap(rfcDataIn);
  ptr e = s + SourceSize(rfcDataIn);
  ptr p = UartparseData(s, e, task);
  if(p != s)
  {
    SourceDrop(rfcDataIn, (uint16) (p - s));
    return 1;
  }
  else
  {
    return 0;
  }
}
#endif
#endif

typedef struct {
  char c;
  int to;
} Arc;

static const Arc arcs[] = {
  { '\t', 0 },
  { ' ', 0 },
  { 'A', 1 },
  { 'T', 2 },
  { '+', 3 },
  { 'A', 4 },
  { 'E', 5 },
  { 'G', 6 },
  { 'H', 7 },
  { 'I', 8 },
  { 'M', 9 },
  { 'P', 10 },
  { 'S', 11 },
  { '2', 12 },
  { 'V', 13 },
  { 'N', 14 },
  { 'A', 15 },
  { 'B', 16 },
  { 'C', 17 },
  { 'L', 18 },
  { 'P', 19 },
  { 'U', 20 },
  { 'V', 21 },
  { 'F', 22 },
  { 'I', 23 },
  { 'N', 24 },
  { 'A', 25 },
  { 'A', 26 },
  { 'B', 27 },
  { 'B', 28 },
  { 'C', 29 },
  { 'L', 30 },
  { 'P', 31 },
  { 'U', 32 },
  { 'D', 33 },
  { 'R', 34 },
  { 'T', 35 },
  { 'T', 36 },
  { 'D', 37 },
  { 'L', 38 },
  { 'D', 39 },
  { 'I', 40 },
  { 'A', 41 },
  { 'E', 42 },
  { 'A', 43 },
  { 'C', 44 },
  { 'D', 45 },
  { 'G', 46 },
  { 'H', 47 },
  { 'M', 48 },
  { 'T', 49 },
  { 'D', 50 },
  { 'Q', 51 },
  { 'P', 52 },
  { 'I', 53 },
  { 'A', 54 },
  { 'D', 55 },
  { 'A', 56 },
  { 'L', 57 },
  { 'D', 58 },
  { 'I', 59 },
  { 'P', 60 },
  { 'A', 61 },
  { 'P', 62 },
  { 'C', 63 },
  { 'E', 64 },
  { 'T', 65 },
  { 'A', 66 },
  { 'A', 67 },
  { 'N', 68 },
  { 'N', 69 },
  { 'R', 70 },
  { 'R', 71 },
  { 'N', 72 },
  { 'O', 73 },
  { 'I', 74 },
  { 'S', 75 },
  { 'A', 76 },
  { 'U', 77 },
  { 'W', 78 },
  { 'C', 79 },
  { 'D', 80 },
  { 'G', 81 },
  { 'K', 82 },
  { 'M', 83 },
  { 'U', 84 },
  { 'C', 85 },
  { 'D', 86 },
  { 'G', 87 },
  { 'R', 88 },
  { 'P', 89 },
  { 'A', 90 },
  { 'N', 91 },
  { 'A', 92 },
  { 'N', 93 },
  { 'N', 94 },
  { 'C', 95 },
  { 'D', 96 },
  { 'G', 97 },
  { 'S', 98 },
  { 'R', 99 },
  { 'C', 100 },
  { 'D', 101 },
  { 'G', 102 },
  { 'P', 103 },
  { 'R', 104 },
  { 'C', 105 },
  { 'D', 106 },
  { 'G', 107 },
  { 'S', 108 },
  { 'D', 109 },
  { 'S', 110 },
  { 'A', 111 },
  { '\n', 112 },
  { '\r', 112 },
  { 'T', 113 },
  { '\n', 114 },
  { '\r', 114 },
  { 'S', 115 },
  { 'N', 116 },
  { 'A', 117 },
  { 'S', 118 },
  { 'T', 119 },
  { 'N', 120 },
  { 'T', 121 },
  { 'A', 122 },
  { 'R', 123 },
  { 'O', 124 },
  { 'I', 125 },
  { 'S', 126 },
  { 'R', 127 },
  { 'R', 128 },
  { ':', -1 },
  { '=', -1 },
  { 'O', 129 },
  { 'I', 130 },
  { 'M', 131 },
  { 'S', 132 },
  { ':', -2 },
  { '=', -2 },
  { 'C', 133 },
  { 'D', 134 },
  { 'G', 135 },
  { 'S', 136 },
  { 'D', 137 },
  { ':', -3 },
  { '=', -3 },
  { 'S', 138 },
  { 'A', 139 },
  { '\n', 140 },
  { '\r', 140 },
  { 'O', 141 },
  { 'I', 142 },
  { 'S', 143 },
  { 'E', 144 },
  { 'T', 145 },
  { 'O', 146 },
  { 'I', 147 },
  { 'S', 148 },
  { 'G', 149 },
  { 'N', 150 },
  { 'P', 151 },
  { 'S', 152 },
  { 'V', 153 },
  { 'P', 154 },
  { 'O', 155 },
  { 'I', 156 },
  { 'S', 157 },
  { 'E', 158 },
  { 'D', 159 },
  { 'S', 160 },
  { 'M', 161 },
  { '\n', -4 },
  { '\r', -4 },
  { '\n', 162 },
  { '\r', 162 },
  { '\n', -5 },
  { '\r', -5 },
  { 'W', 163 },
  { 'N', 164 },
  { 'L', 165 },
  { 'C', 166 },
  { 'A', 167 },
  { 'G', 168 },
  { 'E', 169 },
  { 'H', 170 },
  { 'W', 171 },
  { 'A', 172 },
  { 'N', 173 },
  { 'S', 174 },
  { 'T', 175 },
  { 'P', 176 },
  { 'P', 177 },
  { 'N', 178 },
  { 'S', 179 },
  { 'S', 180 },
  { 'T', 181 },
  { 'O', 182 },
  { 'I', 183 },
  { 'P', 184 },
  { 'S', 185 },
  { 'T', 186 },
  { 'D', 187 },
  { 'S', 188 },
  { 'M', 189 },
  { '\n', -6 },
  { '\r', -6 },
  { 'N', 190 },
  { 'S', 191 },
  { 'T', 192 },
  { 'N', 193 },
  { ':', -7 },
  { '=', -7 },
  { 'N', 194 },
  { 'S', 195 },
  { 'T', 196 },
  { 'S', 197 },
  { 'E', 198 },
  { 'A', 199 },
  { 'L', 200 },
  { 'R', 201 },
  { 'T', 202 },
  { 'O', 203 },
  { 'A', 204 },
  { 'N', 205 },
  { 'S', 206 },
  { 'T', 207 },
  { 'N', 208 },
  { 'R', 209 },
  { '\n', 210 },
  { '\r', 210 },
  { 'E', 211 },
  { '\n', -8 },
  { '\r', -8 },
  { 'E', 212 },
  { ':', -9 },
  { '=', -9 },
  { ':', -10 },
  { '=', -10 },
  { '\n', 213 },
  { '\r', 213 },
  { '\n', 214 },
  { '\r', 214 },
  { 'U', 215 },
  { ':', -11 },
  { '=', -11 },
  { 'T', 216 },
  { 'H', 217 },
  { 'R', 218 },
  { 'H', 219 },
  { 'N', 220 },
  { 'C', 221 },
  { 'A', 222 },
  { 'T', 223 },
  { 'T', 224 },
  { 'N', 225 },
  { 'C', 226 },
  { 'G', 227 },
  { 'A', 228 },
  { 'N', 229 },
  { 'S', 230 },
  { 'B', 231 },
  { 'T', 232 },
  { 'Y', 233 },
  { 'R', 234 },
  { ':', -12 },
  { '=', -12 },
  { 'E', 235 },
  { 'N', 236 },
  { 'C', 237 },
  { 'A', 238 },
  { 'D', 239 },
  { 'N', 240 },
  { 'C', 241 },
  { 'A', 242 },
  { 'T', 243 },
  { 'X', 244 },
  { 'U', 245 },
  { 'A', 246 },
  { 'E', 247 },
  { 'O', 248 },
  { 'L', 249 },
  { 'I', 250 },
  { 'N', 251 },
  { 'C', 252 },
  { 'A', 253 },
  { 'D', 254 },
  { '\n', 255 },
  { '\r', 255 },
  { '\n', -13 },
  { '\r', -13 },
  { '\n', 256 },
  { '\r', 256 },
  { 'R', 257 },
  { '\n', -14 },
  { '\r', -14 },
  { '\n', -15 },
  { '\r', -15 },
  { 'P', 258 },
  { 'W', 259 },
  { 'A', 260 },
  { 'A', 261 },
  { '\n', 262 },
  { '\r', 262 },
  { ':', -16 },
  { '=', -16 },
  { '\n', 263 },
  { '\r', 263 },
  { '\n', 264 },
  { '\r', 264 },
  { ':', -17 },
  { '=', -17 },
  { ':', -18 },
  { '=', -18 },
  { ':', -19 },
  { '=', -19 },
  { '\n', 265 },
  { '\r', 265 },
  { '\n', 266 },
  { '\r', 266 },
  { '\n', 267 },
  { '\r', 267 },
  { 'N', 268 },
  { 'C', 269 },
  { '\n', 270 },
  { '\r', 270 },
  { 'A', 271 },
  { 'P', 272 },
  { ':', -20 },
  { '=', -20 },
  { ':', -21 },
  { '=', -21 },
  { ':', -22 },
  { '=', -22 },
  { '\n', 273 },
  { '\r', 273 },
  { '\n', 274 },
  { '\r', 274 },
  { ':', -23 },
  { '=', -23 },
  { ':', -24 },
  { '=', -24 },
  { '\n', 275 },
  { '\r', 275 },
  { '\n', 276 },
  { '\r', 276 },
  { 'A', 277 },
  { 'T', 278 },
  { 'S', 279 },
  { 'Y', 280 },
  { 'V', 281 },
  { 'P', 282 },
  { 'D', 283 },
  { 'U', 284 },
  { 'R', 285 },
  { ':', -25 },
  { '=', -25 },
  { '\n', 286 },
  { '\r', 286 },
  { '\n', 287 },
  { '\r', 287 },
  { '\n', 288 },
  { '\r', 288 },
  { '\n', -26 },
  { '\r', -26 },
  { '\n', -27 },
  { '\r', -27 },
  { '\n', 289 },
  { '\r', 289 },
  { '\n', 290 },
  { '\r', 290 },
  { '\n', 291 },
  { '\r', 291 },
  { '\n', 292 },
  { '\r', 292 },
  { '\n', 293 },
  { '\r', 293 },
  { '\n', -28 },
  { '\r', -28 },
  { '\n', -29 },
  { '\r', -29 },
  { '\n', -30 },
  { '\r', -30 },
  { '\n', -31 },
  { '\r', -31 },
  { '\n', -32 },
  { '\r', -32 },
  { '\n', -33 },
  { '\r', -33 },
  { ':', -34 },
  { '=', -34 },
  { '\n', 294 },
  { '\r', 294 },
  { '\n', -35 },
  { '\r', -35 },
  { '\n', 295 },
  { '\r', 295 },
  { 'E', 296 },
  { '\n', -36 },
  { '\r', -36 },
  { '\n', -37 },
  { '\r', -37 },
  { '\n', -38 },
  { '\r', -38 },
  { '\n', -39 },
  { '\r', -39 },
  { '\n', 297 },
  { '\r', 297 },
  { '\n', 298 },
  { '\r', 298 },
  { 'E', 299 },
  { '\n', 300 },
  { '\r', 300 },
  { '\n', 301 },
  { '\r', 301 },
  { '\n', 302 },
  { '\r', 302 },
  { 'O', 303 },
  { 'P', 304 },
  { '\n', 305 },
  { '\r', 305 },
  { '\n', -40 },
  { '\r', -40 },
  { '\n', -41 },
  { '\r', -41 },
  { '\n', -42 },
  { '\r', -42 },
  { '\n', -43 },
  { '\r', -43 },
  { '\n', -44 },
  { '\r', -44 },
  { '\n', -45 },
  { '\r', -45 },
  { '\n', -46 },
  { '\r', -46 },
  { '\n', -47 },
  { '\r', -47 },
  { '\n', -48 },
  { '\r', -48 },
  { '\n', -49 },
  { '\r', -49 },
  { ':', -50 },
  { '=', -50 },
  { '\n', -51 },
  { '\r', -51 },
  { '\n', -52 },
  { '\r', -52 },
  { '\n', 306 },
  { '\r', 306 },
  { '\n', -53 },
  { '\r', -53 },
  { '\n', -54 },
  { '\r', -54 },
  { '\n', -55 },
  { '\r', -55 },
  { 'W', 307 },
  { '\n', 308 },
  { '\r', 308 },
  { '\n', -56 },
  { '\r', -56 },
  { '\n', -57 },
  { '\r', -57 },
  { 'N', 309 },
  { '\n', -58 },
  { '\r', -58 },
  { '\n', 310 },
  { '\r', 310 },
  { '\n', -59 },
  { '\r', -59 },
};

static const Arc *const states[312] = {
  &arcs[0],
  &arcs[3],
  &arcs[4],
  &arcs[5],
  &arcs[13],
  &arcs[15],
  &arcs[16],
  &arcs[23],
  &arcs[25],
  &arcs[26],
  &arcs[27],
  &arcs[29],
  &arcs[34],
  &arcs[35],
  &arcs[36],
  &arcs[37],
  &arcs[38],
  &arcs[39],
  &arcs[40],
  &arcs[41],
  &arcs[42],
  &arcs[43],
  &arcs[44],
  &arcs[51],
  &arcs[52],
  &arcs[53],
  &arcs[54],
  &arcs[55],
  &arcs[56],
  &arcs[57],
  &arcs[59],
  &arcs[60],
  &arcs[62],
  &arcs[63],
  &arcs[64],
  &arcs[65],
  &arcs[66],
  &arcs[67],
  &arcs[68],
  &arcs[69],
  &arcs[70],
  &arcs[71],
  &arcs[72],
  &arcs[73],
  &arcs[74],
  &arcs[75],
  &arcs[76],
  &arcs[77],
  &arcs[78],
  &arcs[79],
  &arcs[80],
  &arcs[85],
  &arcs[86],
  &arcs[89],
  &arcs[90],
  &arcs[91],
  &arcs[92],
  &arcs[93],
  &arcs[94],
  &arcs[95],
  &arcs[96],
  &arcs[100],
  &arcs[101],
  &arcs[104],
  &arcs[105],
  &arcs[106],
  &arcs[110],
  &arcs[111],
  &arcs[112],
  &arcs[113],
  &arcs[115],
  &arcs[116],
  &arcs[118],
  &arcs[119],
  &arcs[120],
  &arcs[122],
  &arcs[123],
  &arcs[124],
  &arcs[125],
  &arcs[127],
  &arcs[128],
  &arcs[129],
  &arcs[130],
  &arcs[131],
  &arcs[132],
  &arcs[134],
  &arcs[135],
  &arcs[136],
  &arcs[138],
  &arcs[140],
  &arcs[144],
  &arcs[145],
  &arcs[147],
  &arcs[148],
  &arcs[149],
  &arcs[151],
  &arcs[152],
  &arcs[153],
  &arcs[154],
  &arcs[155],
  &arcs[156],
  &arcs[157],
  &arcs[158],
  &arcs[159],
  &arcs[164],
  &arcs[165],
  &arcs[166],
  &arcs[167],
  &arcs[168],
  &arcs[169],
  &arcs[170],
  &arcs[171],
  &arcs[172],
  &arcs[174],
  &arcs[176],
  &arcs[178],
  &arcs[179],
  &arcs[180],
  &arcs[181],
  &arcs[182],
  &arcs[183],
  &arcs[184],
  &arcs[185],
  &arcs[187],
  &arcs[188],
  &arcs[189],
  &arcs[190],
  &arcs[191],
  &arcs[192],
  &arcs[193],
  &arcs[194],
  &arcs[195],
  &arcs[196],
  &arcs[197],
  &arcs[198],
  &arcs[199],
  &arcs[201],
  &arcs[202],
  &arcs[203],
  &arcs[204],
  &arcs[205],
  &arcs[207],
  &arcs[208],
  &arcs[209],
  &arcs[210],
  &arcs[211],
  &arcs[213],
  &arcs[214],
  &arcs[215],
  &arcs[216],
  &arcs[217],
  &arcs[218],
  &arcs[221],
  &arcs[222],
  &arcs[223],
  &arcs[224],
  &arcs[225],
  &arcs[226],
  &arcs[227],
  &arcs[228],
  &arcs[229],
  &arcs[231],
  &arcs[232],
  &arcs[234],
  &arcs[235],
  &arcs[237],
  &arcs[239],
  &arcs[241],
  &arcs[243],
  &arcs[244],
  &arcs[246],
  &arcs[247],
  &arcs[249],
  &arcs[250],
  &arcs[251],
  &arcs[252],
  &arcs[253],
  &arcs[254],
  &arcs[255],
  &arcs[256],
  &arcs[257],
  &arcs[258],
  &arcs[259],
  &arcs[260],
  &arcs[261],
  &arcs[262],
  &arcs[263],
  &arcs[264],
  &arcs[265],
  &arcs[267],
  &arcs[268],
  &arcs[269],
  &arcs[270],
  &arcs[271],
  &arcs[272],
  &arcs[273],
  &arcs[274],
  &arcs[275],
  &arcs[276],
  &arcs[277],
  &arcs[278],
  &arcs[279],
  &arcs[280],
  &arcs[281],
  &arcs[282],
  &arcs[283],
  &arcs[284],
  &arcs[285],
  &arcs[286],
  &arcs[287],
  &arcs[289],
  &arcs[291],
  &arcs[293],
  &arcs[294],
  &arcs[296],
  &arcs[298],
  &arcs[299],
  &arcs[300],
  &arcs[301],
  &arcs[302],
  &arcs[304],
  &arcs[306],
  &arcs[308],
  &arcs[310],
  &arcs[312],
  &arcs[314],
  &arcs[316],
  &arcs[318],
  &arcs[320],
  &arcs[322],
  &arcs[323],
  &arcs[324],
  &arcs[326],
  &arcs[327],
  &arcs[328],
  &arcs[330],
  &arcs[332],
  &arcs[334],
  &arcs[336],
  &arcs[338],
  &arcs[340],
  &arcs[342],
  &arcs[344],
  &arcs[346],
  &arcs[347],
  &arcs[348],
  &arcs[349],
  &arcs[350],
  &arcs[351],
  &arcs[352],
  &arcs[354],
  &arcs[355],
  &arcs[357],
  &arcs[359],
  &arcs[361],
  &arcs[363],
  &arcs[365],
  &arcs[367],
  &arcs[369],
  &arcs[371],
  &arcs[373],
  &arcs[375],
  &arcs[377],
  &arcs[379],
  &arcs[381],
  &arcs[383],
  &arcs[385],
  &arcs[387],
  &arcs[389],
  &arcs[391],
  &arcs[393],
  &arcs[395],
  &arcs[397],
  &arcs[398],
  &arcs[400],
  &arcs[402],
  &arcs[404],
  &arcs[406],
  &arcs[408],
  &arcs[410],
  &arcs[411],
  &arcs[413],
  &arcs[415],
  &arcs[417],
  &arcs[418],
  &arcs[419],
  &arcs[421],
  &arcs[423],
  &arcs[425],
  &arcs[427],
  &arcs[429],
  &arcs[431],
  &arcs[433],
  &arcs[435],
  &arcs[437],
  &arcs[439],
  &arcs[441],
  &arcs[443],
  &arcs[445],
  &arcs[447],
  &arcs[449],
  &arcs[451],
  &arcs[453],
  &arcs[455],
  &arcs[456],
  &arcs[458],
  &arcs[460],
  &arcs[462],
  &arcs[463],
  &arcs[465],
  &arcs[467],
  &arcs[469],
};

static uint16 matchLiteral(ptr s, ptr e, Task task)
{ s=s; e=e; task=task; return 0; }

ptr UartparseData(ptr s, ptr e, Task task)
{
  ptr p;

#ifdef DISPLAY_AT_CMDS
  {
  	ptr c = s;
    printf("\nreceived: ");
  	while (c != e)
  	{
		if (*c == '\r')			printf("\\r");
		else if (*c == '\n') 	printf("\\n");
		else 					putchar(*c);

		c++;
  	}
  }
#endif

#ifdef TEST_HARNESS
  task = task;
#endif
  for(; (p = findEndOfPacket(s, e)) != 0; s = p)
  {
    if(p == s+1)
    {
      /* Silently discard one character; no packets are that short */
      continue;
    }
    else if(matchLiteral(s, p, task))
    {
      continue;
    }
    else
    {
      union {
        struct DiscoverNearDev DiscoverNearDev;
        struct PairDev PairDev;
        struct SetScanMode SetScanMode;
        struct SetUartBaudrate SetUartBaudrate;
        struct HfpConn HfpConn;
        struct HfpDial HfpDial;
        struct HfpMute HfpMute;
        struct SetDevClass SetDevClass;
        struct HidConn HidConn;
        struct HidKeyboardReport HidKeyboardReport;
        struct HidMouseReport HidMouseReport;
        struct MapConn MapConn;
        struct SetLocalAddr SetLocalAddr;
        struct SetLocalDevName SetLocalDevName;
        struct SppConn SppConn;
        struct SppSendData SppSendData;
        struct A2dpConn A2dpConn;
        struct GattConn GattConn;
        struct PbapConn PbapConn;
        struct PbapSetType PbapSetType;
      } u, *uu = &u;
      int state = 0;
      ptr t = s;
      while(t != e && state >= 0)
      {
        char m = my_toupper((char) *t);
        const Arc *a = states[state];
        const Arc *const last_a = states[state+1];
#ifndef TEST_HARNESS
        a = (const Arc *) (void *) UtilFind(0xFFFF, (uint16) m, (const uint16 *) (void *) &a[0].c, 0, sizeof(Arc), (uint16) (last_a - a));
#endif
#ifdef TEST_HARNESS
        while(a != last_a && a->c != m) a++;
#endif
        /*lint -e{801} suppress goto is deprecated */
        if(!a) goto unrecognised;
        state = a->to;
        ++t;
      }
	  if(0<(-state) && (-state)<60)
      	theUARTTask.uart_src_need_drop = TRUE;
      switch(-state)
      {
        case 1:
          if(match1(match1(UtilGetNumber(t, e, &uu->DiscoverNearDev.start), e), e))
          {
#ifndef TEST_HARNESS
            handleDiscoverNearDev(task, &uu->DiscoverNearDev);
#endif
#ifdef TEST_HARNESS
            printf("Called handleDiscoverNearDev");
            printf(" start=%d", uu->DiscoverNearDev.start);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 2:
          if(match1(match1(getString(t, e, &uu->PairDev.addr), e), e))
          {
#ifndef TEST_HARNESS
            handlePairDev(task, &uu->PairDev);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePairDev");
            printString("addr", &uu->PairDev.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 3:
          if(match1(match1(getString(t, e, &uu->SetScanMode.mode), e), e))
          {
#ifndef TEST_HARNESS
            handleSetScanMode(task, &uu->SetScanMode);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetScanMode");
            printString("mode", &uu->SetScanMode.mode);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 4:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetPin(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetPin");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 5:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetVersion(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetVersion");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 6:
          if(t)
          {
#ifndef TEST_HARNESS
            handleSetPin(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetPin");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 7:
          if(match1(match1(getString(t, e, &uu->SetUartBaudrate.baudrate), e), e))
          {
#ifndef TEST_HARNESS
            handleSetUartBaudrate(task, &uu->SetUartBaudrate);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetUartBaudrate");
            printString("baudrate", &uu->SetUartBaudrate.baudrate);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 8:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetUartBaudrate(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetUartBaudrate");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 9:
          if(match1(match1(getString(t, e, &uu->HfpConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleHfpConn(task, &uu->HfpConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpConn");
            printString("addr", &uu->HfpConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 10:
          if(match1(match1(getString(t, e, &uu->HfpDial.num), e), e))
          {
#ifndef TEST_HARNESS
            handleHfpDial(task, &uu->HfpDial);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpDial");
            printString("num", &uu->HfpDial.num);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 11:
          if(match1(match1(UtilGetNumber(t, e, &uu->HfpMute.mute), e), e))
          {
#ifndef TEST_HARNESS
            handleHfpMute(task, &uu->HfpMute);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpMute");
            printf(" mute=%d", uu->HfpMute.mute);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 12:
          if(match1(match1(getString(t, e, &uu->SetDevClass.cls), e), e))
          {
#ifndef TEST_HARNESS
            handleSetDevClass(task, &uu->SetDevClass);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetDevClass");
            printString("cls", &uu->SetDevClass.cls);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 13:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetDevClass(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetDevClass");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 14:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHfpDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 15:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHfpGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 16:
          if(match1(match1(getString(t, e, &uu->HidConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleHidConn(task, &uu->HidConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHidConn");
            printString("addr", &uu->HidConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 17:
          if(match1(match1(getString(t, e, &uu->HidKeyboardReport.data), e), e))
          {
#ifndef TEST_HARNESS
            handleHidKeyboardReport(task, &uu->HidKeyboardReport);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHidKeyboardReport");
            printString("data", &uu->HidKeyboardReport.data);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 18:
          if(match1(match1(getString(t, e, &uu->HidMouseReport.data), e), e))
          {
#ifndef TEST_HARNESS
            handleHidMouseReport(task, &uu->HidMouseReport);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHidMouseReport");
            printString("data", &uu->HidMouseReport.data);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 19:
          if(match1(match1(getString(t, e, &uu->MapConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleMapConn(task, &uu->MapConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleMapConn");
            printString("addr", &uu->MapConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 20:
          if(match1(match1(getString(t, e, &uu->SetLocalAddr.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleSetLocalAddr(task, &uu->SetLocalAddr);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetLocalAddr");
            printString("addr", &uu->SetLocalAddr.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 21:
          if(match1(match1(getString(t, e, &uu->SetLocalDevName.DevName), e), e))
          {
#ifndef TEST_HARNESS
            handleSetLocalDevName(task, &uu->SetLocalDevName);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSetLocalDevName");
            printString("DevName", &uu->SetLocalDevName.DevName);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 22:
          if(match1(match1(getString(t, e, &uu->SppConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleSppConn(task, &uu->SppConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSppConn");
            printString("addr", &uu->SppConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 23:
          if(match1(match1(getString(t, e, &uu->SppSendData.data), e), e))
          {
#ifndef TEST_HARNESS
            handleSppSendData(task, &uu->SppSendData);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSppSendData");
            printString("data", &uu->SppSendData.data);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 24:
          if(match1(match1(getString(t, e, &uu->A2dpConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleA2dpConn(task, &uu->A2dpConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleA2dpConn");
            printString("addr", &uu->A2dpConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 25:
          if(match1(match1(getString(t, e, &uu->GattConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handleGattConn(task, &uu->GattConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGattConn");
            printString("addr", &uu->GattConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 26:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetLocalAddr(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetLocalAddr");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 27:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGetLocalDevName(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGetLocalDevName");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 28:
          if(t)
          {
#ifndef TEST_HARNESS
            handleThreeWayReleaseAllHeld(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleThreeWayReleaseAllHeld");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 29:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHidDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHidDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 30:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHidGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHidGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 31:
          if(t)
          {
#ifndef TEST_HARNESS
            handleMapDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleMapDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 32:
          if(t)
          {
#ifndef TEST_HARNESS
            handleMapGetMessage(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleMapGetMessage");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 33:
          if(t)
          {
#ifndef TEST_HARNESS
            handleMapGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleMapGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 34:
          if(match1(match1(getString(t, e, &uu->PbapConn.addr), e), e))
          {
#ifndef TEST_HARNESS
            handlePbapConn(task, &uu->PbapConn);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePbapConn");
            printString("addr", &uu->PbapConn.addr);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 35:
          if(t)
          {
#ifndef TEST_HARNESS
            handlePbapGetPhoneBook(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePbapGetPhoneBook");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 36:
          if(t)
          {
#ifndef TEST_HARNESS
            handleSppDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSppDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 37:
          if(t)
          {
#ifndef TEST_HARNESS
            handleSppGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleSppGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 38:
          if(t)
          {
#ifndef TEST_HARNESS
            handleA2dpDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleA2dpDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 39:
          if(t)
          {
#ifndef TEST_HARNESS
            handleA2dpGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleA2dpGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 40:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGattDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGattDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 41:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGattGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGattGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 42:
          if(t)
          {
#ifndef TEST_HARNESS
            handleGattSendData(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleGattSendData");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 43:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHfpAnswer(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpAnswer");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 44:
          if(t)
          {
#ifndef TEST_HARNESS
            handleHfpHangUp(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleHfpHangUp");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 45:
          if(t)
          {
#ifndef TEST_HARNESS
            handleThreeWayAddHeldTo3Way(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleThreeWayAddHeldTo3Way");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 46:
          if(t)
          {
#ifndef TEST_HARNESS
            handleThreeWayAcceptWaitingHoldActive(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleThreeWayAcceptWaitingHoldActive");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 47:
          if(t)
          {
#ifndef TEST_HARNESS
            handleThreeWayAcceptWaitingReleaseActive(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleThreeWayAcceptWaitingReleaseActive");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 48:
          if(t)
          {
#ifndef TEST_HARNESS
            handlePbapDisc(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePbapDisc");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 49:
          if(t)
          {
#ifndef TEST_HARNESS
            handlePbapGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePbapGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 50:
          if(match1(match1(UtilGetNumber(t, e, &uu->PbapSetType.type), e), e))
          {
#ifndef TEST_HARNESS
            handlePbapSetType(task, &uu->PbapSetType);
#endif
#ifdef TEST_HARNESS
            printf("Called handlePbapSetType");
            printf(" type=%d", uu->PbapSetType.type);
            putchar('\n');
#endif
            continue;
          }
          break;
        case 51:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpGetStatus(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpGetStatus");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 52:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpNext(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpNext");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 53:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpPlay(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpPlay");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 54:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpPrev(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpPrev");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 55:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpStop(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpStop");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 56:
          if(t)
          {
#ifndef TEST_HARNESS
            handleEnterPair(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleEnterPair");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 57:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpPause(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpPause");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 58:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpVolUp(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpVolUp");
            putchar('\n');
#endif
            continue;
          }
          break;
        case 59:
          if(t)
          {
#ifndef TEST_HARNESS
            handleAvrcpVolDown(task);
#endif
#ifdef TEST_HARNESS
            printf("Called handleAvrcpVolDown");
            putchar('\n');
#endif
            continue;
          }
          break;
        default:
          break;
      }
      /*
        The message does not contain a recognised AT command or response.
        Pass the data on to the application to have a go at 
      */
unrecognised:
#ifndef TEST_HARNESS
      UarthandleUnrecognised(s, (uint16) (p-s), task);
		theUARTTask.uart_src_need_drop = TRUE;
#endif
#ifdef TEST_HARNESS
      printf("Called handleUnrecognised\n");
#endif
    }
  }

  return s;
}

/*
handleGetVersion
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar V
   MatchChar E
   MatchChar R
   Match "\r\n"
   Match "\r\n"


handleGetLocalAddr
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar B
   MatchChar D
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   Match "\r\n"
   Match "\r\n"


handleSetLocalAddr
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar B
   MatchChar D
   MatchChar A
   MatchChar D
   MatchChar D
   MatchChar R
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleGetLocalDevName
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar L
   MatchChar D
   MatchChar N
   MatchChar A
   MatchChar M
   MatchChar E
   Match "\r\n"
   Match "\r\n"


handleSetLocalDevName
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar L
   MatchChar D
   MatchChar N
   MatchChar A
   MatchChar M
   MatchChar E
   Match "=:"
   GetString DevName
   Match "\r\n"
   Match "\r\n"


handleGetPin
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar P
   MatchChar I
   MatchChar N
   Match "\r\n"
   Match "\r\n"


handleSetPin
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar P
   MatchChar I
   MatchChar N
   Match "\r\n"
   Match "\r\n"


handleGetDevClass
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar C
   MatchChar L
   MatchChar A
   MatchChar S
   MatchChar S
   Match "\r\n"
   Match "\r\n"


handleSetDevClass
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar C
   MatchChar L
   MatchChar A
   MatchChar S
   MatchChar S
   Match "=:"
   GetString cls
   Match "\r\n"
   Match "\r\n"


handleDiscoverNearDev
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar I
   MatchChar N
   MatchChar Q
   MatchChar U
   Match "=:"
   GetNumber start
   Match "\r\n"
   Match "\r\n"


handlePairDev
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar A
   MatchChar I
   MatchChar R
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleSetScanMode
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar C
   MatchChar A
   MatchChar N
   Match "=:"
   GetString mode
   Match "\r\n"
   Match "\r\n"


handleEnterPair
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar E
   MatchChar N
   MatchChar T
   MatchChar E
   MatchChar R
   MatchChar P
   MatchChar A
   MatchChar I
   MatchChar R
   Match "\r\n"
   Match "\r\n"


handleGetUartBaudrate
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar U
   MatchChar A
   MatchChar R
   MatchChar T
   Match "\r\n"
   Match "\r\n"


handleSetUartBaudrate
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar U
   MatchChar A
   MatchChar R
   MatchChar T
   Match "=:"
   GetString baudrate
   Match "\r\n"
   Match "\r\n"


handleHfpGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleHfpConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleHfpDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleHfpAnswer
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar A
   MatchChar N
   MatchChar S
   MatchChar W
   MatchChar E
   MatchChar R
   Match "\r\n"
   Match "\r\n"


handleHfpHangUp
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar H
   MatchChar A
   MatchChar N
   MatchChar G
   MatchChar U
   MatchChar P
   Match "\r\n"
   Match "\r\n"


handleHfpDial
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar D
   MatchChar I
   MatchChar A
   MatchChar L
   Match "=:"
   GetString num
   Match "\r\n"
   Match "\r\n"


handleHfpMute
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar M
   MatchChar U
   MatchChar T
   MatchChar E
   Match "=:"
   GetNumber mute
   Match "\r\n"
   Match "\r\n"


handleThreeWayReleaseAllHeld
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar T
   MatchChar W
   MatchChar R
   MatchChar A
   MatchChar H
   Match "\r\n"
   Match "\r\n"


handleThreeWayAcceptWaitingReleaseActive
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar T
   MatchChar W
   MatchChar A
   MatchChar W
   MatchChar R
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleThreeWayAcceptWaitingHoldActive
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar T
   MatchChar W
   MatchChar A
   MatchChar W
   MatchChar H
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleThreeWayAddHeldTo3Way
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar F
   MatchChar T
   MatchChar W
   MatchChar A
   MatchChar H
   MatchChar T
   MatchChar W
   Match "\r\n"
   Match "\r\n"


handleA2dpGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar 2
   MatchChar D
   MatchChar P
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleA2dpConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar 2
   MatchChar D
   MatchChar P
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleA2dpDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar 2
   MatchChar D
   MatchChar P
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleAvrcpGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleAvrcpPlay
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar P
   MatchChar L
   MatchChar A
   MatchChar Y
   Match "\r\n"
   Match "\r\n"


handleAvrcpPause
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar P
   MatchChar A
   MatchChar U
   MatchChar S
   MatchChar E
   Match "\r\n"
   Match "\r\n"


handleAvrcpStop
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar S
   MatchChar T
   MatchChar O
   MatchChar P
   Match "\r\n"
   Match "\r\n"


handleAvrcpNext
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar N
   MatchChar E
   MatchChar X
   MatchChar T
   Match "\r\n"
   Match "\r\n"


handleAvrcpPrev
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar P
   MatchChar R
   MatchChar E
   MatchChar V
   Match "\r\n"
   Match "\r\n"


handleAvrcpVolUp
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar V
   MatchChar O
   MatchChar L
   MatchChar U
   MatchChar P
   Match "\r\n"
   Match "\r\n"


handleAvrcpVolDown
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar A
   MatchChar V
   MatchChar R
   MatchChar C
   MatchChar P
   MatchChar V
   MatchChar O
   MatchChar L
   MatchChar D
   MatchChar O
   MatchChar W
   MatchChar N
   Match "\r\n"
   Match "\r\n"


handlePbapGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar P
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handlePbapConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar P
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handlePbapDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar P
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handlePbapSetType
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar P
   MatchChar S
   MatchChar T
   MatchChar Y
   MatchChar P
   MatchChar E
   Match "=:"
   GetNumber type
   Match "\r\n"
   Match "\r\n"


handlePbapGetPhoneBook
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar P
   MatchChar B
   MatchChar A
   MatchChar P
   MatchChar G
   MatchChar P
   MatchChar B
   Match "\r\n"
   Match "\r\n"


handleMapGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar M
   MatchChar A
   MatchChar P
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleMapConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar M
   MatchChar A
   MatchChar P
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleMapDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar M
   MatchChar A
   MatchChar P
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleMapGetMessage
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar M
   MatchChar A
   MatchChar P
   MatchChar G
   MatchChar M
   MatchChar S
   MatchChar G
   Match "\r\n"
   Match "\r\n"


handleHidGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar I
   MatchChar D
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleHidConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar I
   MatchChar D
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleHidDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar I
   MatchChar D
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleHidKeyboardReport
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar I
   MatchChar D
   MatchChar K
   MatchChar R
   MatchChar P
   MatchChar T
   Match "=:"
   GetString data
   Match "\r\n"
   Match "\r\n"


handleHidMouseReport
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar H
   MatchChar I
   MatchChar D
   MatchChar M
   MatchChar R
   MatchChar P
   MatchChar T
   Match "=:"
   GetString data
   Match "\r\n"
   Match "\r\n"


handleSppGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar P
   MatchChar P
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleSppConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar P
   MatchChar P
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleSppDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar P
   MatchChar P
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleSppSendData
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar S
   MatchChar P
   MatchChar P
   MatchChar S
   MatchChar E
   MatchChar N
   MatchChar D
   Match "=:"
   GetString data
   Match "\r\n"
   Match "\r\n"


handleGattGetStatus
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar G
   MatchChar S
   MatchChar T
   MatchChar A
   Match "\r\n"
   Match "\r\n"


handleGattConn
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar C
   MatchChar O
   MatchChar N
   MatchChar N
   Match "=:"
   GetString addr
   Match "\r\n"
   Match "\r\n"


handleGattDisc
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar D
   MatchChar I
   MatchChar S
   MatchChar C
   Match "\r\n"
   Match "\r\n"


handleGattSendData
   Skip " \t"
   MatchChar A
   MatchChar T
   MatchChar +
   MatchChar G
   MatchChar A
   MatchChar T
   MatchChar T
   MatchChar S
   MatchChar E
   MatchChar N
   MatchChar D
   Match "\r\n"
   Match "\r\n"


*/
