asm_files = cmpd100.asm \
delay.asm \
mute_control.asm \
peak_monitor.asm \
peq.asm \
hq_peq.asm \
stereo_3d_enhancement.asm \
stream_gain.asm \
stream_mixer.asm \
stereo_copy.asm \
bass_management.asm \
dbe.asm \
dbe_variables.asm \
spkr_ctrl_system.asm \
latency_measure.asm \
volume_and_limit.asm \
meloD_expansion.asm \
vse.asm \
vse_variables.asm


header_files = audio_proc_library.h \
cmpd100.h \
delay.h \
mute_control.h \
peak_monitor.h \
peq.h \
stereo_3d_enhancement.h \
stream_gain.h \
stream_mixer.h \
stereo_copy.h \
bass_management.h \
dbe.h \
spkr_ctrl_system.h \
latency_measure.h \
volume_and_limit.h \
meloD_expansion.h \
vse.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# one line per variant...
$(eval $(call rules_variant,debug,$(FL_DEBUG),$(asm_files)))

# some base register variants
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,base_regs,$(FL_BASE_REG),$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_patch_libs,$(FL_BASE_REG) $(FL_PATCH),$(asm_files),$(hw))) \
)
