dm_asm_files = malloc.asm

pm_asm_files = malloc_pm.asm

asm_files = $(dm_asm_files) $(pm_asm_files)

header_files = malloc.h \
malloc_library.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# dm and pm only versions
$(eval $(call rules_variant,dm,                                                                       ,$(dm_asm_files)))
$(eval $(call rules_variant,pm,                                                                       ,$(pm_asm_files)))

# debug, patch and extra debug variants
$(eval $(call rules_variant,debug,                                             $(FL_DEBUG)            ,$(asm_files)))
$(eval $(call rules_variant,patch_libs,                                                    $(FL_PATCH),$(asm_files)))
$(eval $(call rules_variant,extra_space_debug,           -DINCLUDE_DEBUG_SPACE $(FL_DEBUG)            ,$(asm_files)))
$(eval $(call rules_variant,extra_space_debug_patch_libs,-DINCLUDE_DEBUG_SPACE $(FL_DEBUG) $(FL_PATCH),$(asm_files)))

# debug, patch and extra debug variants with base register support
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,base_regs,                             $(FL_BASE_REG)                                              ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_patch_libs,                  $(FL_BASE_REG)                                   $(FL_PATCH),$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_extra_space_debug,           $(FL_BASE_REG) -DINCLUDE_DEBUG_SPACE $(FL_DEBUG)            ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_extra_space_debug_patch_libs,$(FL_BASE_REG) -DINCLUDE_DEBUG_SPACE $(FL_DEBUG) $(FL_PATCH),$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_dm,                          $(FL_BASE_REG)                                              ,$(dm_asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_pm,                          $(FL_BASE_REG)                                              ,$(pm_asm_files),$(hw))) \
)


