asm_files = stream_decode.asm \
stream_decode_sync.asm \
stream_encode.asm \
stream_encode_mux.asm \
stream_relay.asm \
av_decode.asm \
av_encode.asm

header_files = codec_library.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# one line per variant...
$(eval $(call rules_variant,debug,$(FL_DEBUG),$(asm_files)))

# L2CAP variants
FLAG_L2CAP = -DL2CAP_FRAME

FLAGS_l2cap                  := $(FLAG_L2CAP)
FLAGS_l2cap_debug            := $(FLAG_L2CAP) $(FL_DEBUG)
# FLAGS_l2cap_patch_libs       := $(FLAG_L2CAP)             $(FL_PATCH)
# FLAGS_l2cap_debug_patch_libs := $(FLAG_L2CAP) $(FL_DEBUG) $(FL_PATCH)
$(eval $(call rules_variant,l2cap,                                  $(FLAGS_l2cap),$(asm_files)))
$(eval $(call rules_variant,l2cap_debug,                      $(FLAGS_l2cap_debug),$(asm_files)))
#$(eval $(call rules_variant,l2cap_patch_libs,            $(FLAGS_l2cap_patch_libs),$(asm_files)))
#$(eval $(call rules_variant,l2cap_debug_patch_libs,$(FLAGS_l2cap_debug_patch_libs),$(asm_files)))

# base register variants
FLAGS_base_regs                        := $(FL_BASE_REG)
FLAGS_base_regs_debug                  := $(FL_BASE_REG)               $(FL_DEBUG)
FLAGS_l2cap_base_regs                  := $(FL_BASE_REG) $(FLAG_L2CAP)
# FLAGS_l2cap_base_regs_patch_libs       := $(FL_BASE_REG) $(FLAG_L2CAP)             $(FL_PATCH)
# FLAGS_l2cap_base_regs_debug_patch_libs := $(FL_BASE_REG) $(FLAG_L2CAP) $(FL_DEBUG) $(FL_PATCH)
#$(foreach hw,$(KAL_BASE_REG_CORES), \
#  $(eval $(call rules_variant_core,base_regs,                                              $(FLAGS_base_regs),$(asm_files),$(hw))) \
#  $(eval $(call rules_variant_core,base_regs_debug,                                  $(FLAGS_base_regs_debug),$(asm_files),$(hw))) \
#  $(eval $(call rules_variant_core,l2cap_base_regs,                                  $(FLAGS_l2cap_base_regs),$(asm_files),$(hw))) \
#  $(eval $(call rules_variant_core,l2cap_base_regs_patch_libs,            $(FLAGS_l2cap_base_regs_patch_libs),$(asm_files),$(hw))) \
#  $(eval $(call rules_variant_core,l2cap_base_regs_debug_patch_libs,$(FLAGS_l2cap_base_regs_debug_patch_libs),$(asm_files),$(hw))) \
#)



