/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_heart_rate_server/gatt_heart_rate_server_db.dbi_
 */
#ifndef __GATT_HEART_RATE_SERVER_DB_H
#define __GATT_HEART_RATE_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_HEART_RATE_SERVICE       (0x0001)
#define HANDLE_HEART_RATE_SERVICE_END   (0xffff)
#define HANDLE_HEART_RATE_MEASUREMENT   (0x0003)
#define HANDLE_HEART_RATE_MEASUREMENT_CLIENT_CONFIG (0x0004)
#define HANDLE_BODY_SENSOR_LOCATION     (0x0006)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
