asm_files = patch.asm \
kap_loader.asm

header_files = patch.h \
patch_library.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# one line per variant...
$(eval $(call rules_variant,debug,$(FL_DEBUG),$(asm_files)))

# patch variant for all cores
$(eval $(call rules_variant,patch_libs,$(FL_PATCH),$(asm_files)))

# base register variants
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,base_regs,           $(FL_BASE_REG)            ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_patch_libs,$(FL_BASE_REG) $(FL_PATCH),$(asm_files),$(hw))) \
)

