#ifndef __GATT_CUSTOM_SERVER_UUID__
#define __GATT_CUSTOM_SERVER_UUID__

#define UUID_CUSTOM_SERVICE			0xFF00
#define UUID_CUSTOM_CHARA_WRITE		0xFF01
#define UUID_CUSTOM_CHARA_READ		0xFF02
#define UUID_CUSTOM_CHARA_FLOW_CTL	0xFF03

#endif
