asm_files=cbuffer.asm \
error.asm \
flash.asm \
fwrandom.asm \
interrupt.asm \
message.asm \
pio.asm \
profiler.asm \
pskey.asm \
reset.asm \
stack.asm \
timer.asm \
wall_clock.asm



header_files=cbuffer.h \
core_library.h \
flash.h \
fwrandom.h \
interrupt.h \
kalsim.h \
message.h \
profiler.h \
pio.h \
pskey.h \
stack.h \
timer.h \
wall_clock.h \
core_library_c_stubs.h


$(eval $(call header_rules,$(header_files)))

$(eval $(call rules,$(asm_files)))

# one line per variant...
$(eval $(call rules_variant,debug,$(FL_DEBUG),$(asm_files)))
$(eval $(call rules_variant,compact,-DCOMPACT,$(asm_files)))

$(eval $(call rules_variant,big_stack,-DBUILD_WITH_BIG_STACK,$(asm_files)))



# some base register variants
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,base_regs,                         $(FL_BASE_REG)                                 ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_big_stack,               $(FL_BASE_REG) -DBUILD_WITH_BIG_STACK          ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_debug,                   $(FL_BASE_REG) $(FL_DEBUG)                     ,$(asm_files),$(hw))) \
  $(eval $(call rules_variant_core,base_regs_debug_wall_clock_fail_ok,$(FL_BASE_REG) $(FL_DEBUG) -DWALL_CLOCK_FAIL_OK,$(asm_files),$(hw))) \
)

# c support is only in ARCH3 chips
c_support_files=$(asm_files) core_library_c_stubs.asm crt0_withputchar.asm
$(foreach hw,$(KAL_BASE_REG_CORES), \
  $(eval $(call rules_variant_core,c_support,-DBUILD_WITH_C_SUPPORT,$(c_support_files),$(hw))) \
)

# some specific debug builds
$(eval $(call rules_variant,old_bt_address,                      -DOLD_BT_ADDRESS                     ,$(asm_files)))
$(eval $(call rules_variant,old_bt_address_debug,    $(FL_DEBUG) -DOLD_BT_ADDRESS                     ,$(asm_files)))
$(eval $(call rules_variant,debug_wall_clock_fail_ok,$(FL_DEBUG)                  -DWALL_CLOCK_FAIL_OK,$(asm_files)))





