/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_gap_server/gatt_gap_server_db.dbi_
 */
#ifndef __GATT_GAP_SERVER_DB_H
#define __GATT_GAP_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_GAP_SERVICE              (0x0001)
#define HANDLE_GAP_SERVICE_END          (0xffff)
#define HANDLE_DEVICE_NAME              (0x0003)
#define HANDLE_DEVICE_APPEARANCE        (0x0005)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
