/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_transmit_power_server/gatt_transmit_power_server_db.dbi_
 */
#ifndef __GATT_TRANSMIT_POWER_SERVER_DB_H
#define __GATT_TRANSMIT_POWER_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_TRANSMIT_POWER_SERVER_SERVICE (0x0001)
#define HANDLE_TRANSMIT_POWER_SERVER_SERVICE_END (0xffff)
#define HANDLE_TRANSMIT_POWER_LEVEL     (0x0003)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
