/* Copyright (c) 2001 - 2016 Qualcomm Technologies International, Ltd. */
/* All Rights Reserved. */
/* Qualcomm Technologies International, Ltd. Confidential and Proprietary. */
/* Autogenerated from ps_if.h by Makefile in devHost/gcc/library */
/* This is a selection of values from psbc_keys.h published to the VM */

#ifndef __APP_PS_IF_H__
#define __APP_PS_IF_H__

typedef uint16 pskey;

#define PSKEY_HOST_INTERFACE (((500))+5)
#define PSKEY_MKT_TASK_ACTIVE (((500))+6)
#define PSKEY_IPV4_STATIC_ADDR (((850))+3)
#define PSKEY_IPV4_STATIC_SUBNET_MASK (((850))+6)
#define PSKEY_MDNS_NAME (((850))+8)
#define PSKEY_FIXED_PIN (((850))+9)
#define PSKEY_PIO_WAKEUP_STATE (((900))+27)

#endif
