/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gaia/gaia_db.dbi_
 */
#ifndef __GAIA_DB_H
#define __GAIA_DB_H

#include <csrtypes.h>

#define HANDLE_GAIA_SERVICE             (0x0001)
#define HANDLE_GAIA_SERVICE_END         (0xffff)
#define HANDLE_GAIA_COMMAND_ENDPOINT    (0x0003)
#define HANDLE_GAIA_RESPONSE_ENDPOINT   (0x0005)
#define HANDLE_GAIA_RESPONSE_CLIENT_CONFIG (0x0006)
#define HANDLE_GAIA_DATA_ENDPOINT       (0x0008)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
